// File generated by flutterfire configure (soz-sende-app).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeGO5mufMDcClX-k-O1QTy4fZ_RXyiFg',
    appId: '1:716746082623:android:1ce74273b1a56fc1be2b8a',
    messagingSenderId: '716746082623',
    projectId: 'soz-sende-app',
    storageBucket: 'soz-sende-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXBkCICWaF2fnXeS_SNOj9n-tjHf5PDk',
    appId: '1:716746082623:ios:9b725b4570e57b1bbe2b8a',
    messagingSenderId: '716746082623',
    projectId: 'soz-sende-app',
    storageBucket: 'soz-sende-app.firebasestorage.app',
    iosClientId: '716746082623-v3cs12rgko5e8v781f3d4vb2j5nctqiu.apps.googleusercontent.com',
    iosBundleId: 'com.youhavetosay.youHaveToSay',
  );

}